on: [push]

jobs:
  auto_version_changelog:
    runs-on: ubuntu-latest
    steps:

      - name: finding python3 version
        run: python3 --version

      - id: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: finding python3 version
        run: python3 --version

      - name: Auto-generate changelog and increment version
        uses: uScheduleMe/auto-version-changelog@other
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
